abs_action: false
dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  abs_action: false
  dataset_path: /media/hdd/yixiao/mimicgen/datasets/core/pick_place_d0.hdf5
  horizon: 10
  n_obs_steps: 2
  pad_after: 7
  pad_before: 1
  rotation_rep: rotation_6d
  seed: 42
  shape_meta:
    action:
      shape:
      - 7
    obs:
      agentview_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
  use_cache: true
  val_ratio: 0.02
dataset_path: /media/hdd/yixiao/mimicgen/datasets/core/pick_place_d0.hdf5
env_runner:
  _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
  abs_action: false
  crf: 22
  dataset_path: /media/hdd/yixiao/mimicgen/datasets/core/pick_place_d0.hdf5
  fps: 10
  max_steps: 400
  n_action_steps: 8
  n_envs: 28
  n_obs_steps: 2
  n_test: 50
  n_test_vis: 4
  n_train: 6
  n_train_vis: 2
  past_action: false
  render_obs_key: agentview_image
  shape_meta:
    action:
      shape:
      - 7
    obs:
      agentview_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_eef_pos:
        shape:
        - 3
      robot0_eef_quat:
        shape:
        - 4
      robot0_eye_in_hand_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      robot0_gripper_qpos:
        shape:
        - 2
  test_start_seed: 100000
  tqdm_interval_sec: 1.0
  train_start_idx: 0
name: pick_place_d0
shape_meta:
  action:
    shape:
    - 7
  obs:
    agentview_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot0_eef_pos:
      shape:
      - 3
    robot0_eef_quat:
      shape:
      - 4
    robot0_eye_in_hand_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    robot0_gripper_qpos:
      shape:
      - 2
task_name: pick_place_d0
